version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - user=${USER}
        - group=${GROUP}
        - uid=${UID}
        - gid=${GID}
    container_name: MAPP_Strabismus_api
    ports:
      - '3000:8000'
    environment:
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
    volumes:
      - ./ai_models:/code/ai_models:ro
      - ./runs:/code/runs
      - ./app/uploads:/code/app/uploads
      - ./app/tmp:/code/app/tmp
    restart: always

  db:
    image: postgres:16-alpine
    container_name: MAPP_Strabismus_postgres_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
    volumes:
      - MAPP_Strabismus_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  MAPP_Strabismus_pgdata: