version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MAPP_Strabismus_api
    ports:
      - '3000:8000'
    environment:
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
    volumes:
      - ./ai_models:/code/ai_models:ro
      - ./app/uploads:/code/app/uploads
      - ./app/tmp:/code/app/tmp
    restart: always

  db:
    image: postgres:16-alpine
    container_name: MAPP_Strabismus_postgres_db
    environment:
      - POSTGRES_PASSWORD=change_this
      - POSTGRES_USER=change_this
      - POSTGRES_DB=change_this
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
    volumes:
      - MAPP_Strabismus_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  MAPP_Strabismus_pgdata: